name: Build Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Publish zItemStacker
    uses: GroupeZ-dev/actions/.github/workflows/build.yml@main
    with:
      project-name: "zItemStacker"
      publish: true
      project-to-publish: "API:publish"
      discord-avatar-url: "https://groupez.dev/storage/images/15.png"
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
